import { readdirSync, readFileSync, statSync, watch, writeFileSync } from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const srcDir = path.resolve(__dirname, '../src')

/**
 * Check if a file contains `export default`.
 * Returns the default export identifier name, or null if none found.
 */
function getDefaultExportName(filePath: string): string | null {
  const content = readFileSync(filePath, 'utf-8')

  // export default function Foo / export default class Foo
  const declMatch = content.match(/export\s+default\s+(?:function|class)\s+(\w+)/)
  if (declMatch) return declMatch[1]

  // export default Foo (identifier)
  const idMatch = content.match(/export\s+default\s+([A-Z]\w*)/)
  if (idMatch) return idMatch[1]

  // Anonymous: export default function() / export default () =>
  if (/export\s+default\s/.test(content)) return null

  return null
}

/**
 * Generate export lines for a module, handling both named and default exports.
 */
function genExportLines(filePath: string, importPath: string): string[] {
  const lines: string[] = []
  lines.push(`export * from '${importPath}'`)

  const defaultName = getDefaultExportName(filePath)
  if (defaultName) {
    lines.push(`export { default as ${defaultName} } from '${importPath}'`)
  }

  return lines
}

/**
 * Recursively collect all .ts/.tsx files under a directory.
 * Returns paths relative to the given base directory, sorted.
 */
function collectFiles(dir: string, ext: string[], base: string = dir): string[] {
  const results: string[] = []
  for (const entry of readdirSync(dir).sort()) {
    const fullPath = path.join(dir, entry)
    if (statSync(fullPath).isDirectory()) {
      results.push(...collectFiles(fullPath, ext, base))
    } else if (ext.some((e) => entry.endsWith(e))) {
      results.push(path.relative(base, fullPath))
    }
  }
  return results
}

function generate(): void {
  const lines: string[] = [
    '// Auto-generated by scripts/gen-index.ts',
    '// Do not edit manually',
    '',
  ]

  // utils
  lines.push('// utils')
  lines.push("export { cn } from './lib/utils'")
  lines.push('')

  // hooks
  const hooksDir = path.join(srcDir, 'hooks')
  const hooks = collectFiles(hooksDir, ['.ts', '.tsx'])

  if (hooks.length) {
    lines.push('// hooks')
    for (const relPath of hooks) {
      const name = relPath.replace(/\.tsx?$/, '')
      const filePath = path.join(hooksDir, relPath)
      lines.push(...genExportLines(filePath, `./hooks/${name}`))
    }
    lines.push('')
  }

  // components — recursively scan all subdirectories under components/
  const componentsDir = path.join(srcDir, 'components')
  const components = collectFiles(componentsDir, ['.tsx'])

  let defaultExportCount = 0

  if (components.length) {
    lines.push('// components')
    for (const relPath of components) {
      const name = relPath.replace(/\.tsx$/, '')
      const filePath = path.join(componentsDir, relPath)
      const exportLines = genExportLines(filePath, `./components/${name}`)
      lines.push(...exportLines)
      if (exportLines.length > 1) defaultExportCount++
    }
    lines.push('')
  }

  const output = lines.join('\n')
  const target = path.join(srcDir, 'index.ts')
  writeFileSync(target, output, 'utf-8')

  console.log(
    `Generated src/index.ts with ${hooks.length} hooks, ${components.length} components` +
      (defaultExportCount > 0 ? `, ${defaultExportCount} default exports forwarded` : ''),
  )
}

// Run once
generate()

// Watch mode: --watch flag
if (process.argv.includes('--watch')) {
  const watchDirs = [path.join(srcDir, 'components'), path.join(srcDir, 'hooks')]

  let debounceTimer: ReturnType<typeof setTimeout> | null = null

  function onFileChange(_dir: string, filename: string | null): void {
    // Only react to .ts/.tsx file changes
    if (filename && !/\.tsx?$/.test(filename)) return

    // Debounce rapid successive events
    if (debounceTimer) clearTimeout(debounceTimer)
    debounceTimer = setTimeout(() => {
      console.log(`[watch] Change detected${filename ? `: ${filename}` : ''}, regenerating...`)
      generate()
    }, 200)
  }

  for (const dir of watchDirs) {
    watch(dir, { recursive: true }, (_, filename) => onFileChange(dir, filename))
  }

  console.log('[watch] Watching for changes in components/ and hooks/...')
}
