import { readdirSync, writeFileSync } from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const srcDir = path.resolve(__dirname, '../src')

const lines: string[] = ['// Auto-generated by scripts/gen-index.ts', '// Do not edit manually', '']

// utils
lines.push('// utils')
lines.push("export { cn } from './lib/utils'")
lines.push('')

// hooks
const hooksDir = path.join(srcDir, 'hooks')
const hooks = readdirSync(hooksDir)
  .filter((f) => f.endsWith('.ts') || f.endsWith('.tsx'))
  .sort()

if (hooks.length) {
  lines.push('// hooks')
  for (const file of hooks) {
    const name = file.replace(/\.tsx?$/, '')
    lines.push(`export * from './hooks/${name}'`)
  }
  lines.push('')
}

// components
const componentsDir = path.join(srcDir, 'components/ui')
const components = readdirSync(componentsDir)
  .filter((f) => f.endsWith('.tsx'))
  .sort()

if (components.length) {
  lines.push('// components')
  for (const file of components) {
    const name = file.replace(/\.tsx$/, '')
    lines.push(`export * from './components/ui/${name}'`)
  }
  lines.push('')
}

const output = lines.join('\n')
const target = path.join(srcDir, 'index.ts')
writeFileSync(target, output, 'utf-8')

console.log(`Generated src/index.ts with ${hooks.length} hooks and ${components.length} components`)
