/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/_dashboard'
import { Route as DashboardIndexRouteImport } from './routes/_dashboard/index'
import { Route as DashboardAboutRouteImport } from './routes/_dashboard/about'
import { Route as DashboardDocsButtonRouteImport } from './routes/_dashboard/docs.button'

const DashboardRoute = DashboardRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAboutRoute = DashboardAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDocsButtonRoute = DashboardDocsButtonRouteImport.update({
  id: '/docs/button',
  path: '/docs/button',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof DashboardIndexRoute
  '/about': typeof DashboardAboutRoute
  '/docs/button': typeof DashboardDocsButtonRoute
}
export interface FileRoutesByTo {
  '/about': typeof DashboardAboutRoute
  '/': typeof DashboardIndexRoute
  '/docs/button': typeof DashboardDocsButtonRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_dashboard': typeof DashboardRouteWithChildren
  '/_dashboard/about': typeof DashboardAboutRoute
  '/_dashboard/': typeof DashboardIndexRoute
  '/_dashboard/docs/button': typeof DashboardDocsButtonRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/docs/button'
  fileRoutesByTo: FileRoutesByTo
  to: '/about' | '/' | '/docs/button'
  id:
    | '__root__'
    | '/_dashboard'
    | '/_dashboard/about'
    | '/_dashboard/'
    | '/_dashboard/docs/button'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DashboardRoute: typeof DashboardRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/': {
      id: '/_dashboard/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/about': {
      id: '/_dashboard/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof DashboardAboutRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/docs/button': {
      id: '/_dashboard/docs/button'
      path: '/docs/button'
      fullPath: '/docs/button'
      preLoaderRoute: typeof DashboardDocsButtonRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardAboutRoute: typeof DashboardAboutRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardDocsButtonRoute: typeof DashboardDocsButtonRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAboutRoute: DashboardAboutRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardDocsButtonRoute: DashboardDocsButtonRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  DashboardRoute: DashboardRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
