/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/_dashboard'
import { Route as DashboardIndexRouteImport } from './routes/_dashboard/index'
import { Route as DashboardDocsStaggerRevealRouteImport } from './routes/_dashboard/docs.stagger-reveal'
import { Route as DashboardDocsSilkRouteImport } from './routes/_dashboard/docs.silk'
import { Route as DashboardDocsLoadingPageRouteImport } from './routes/_dashboard/docs.loading-page'
import { Route as DashboardDocsAuroraRouteImport } from './routes/_dashboard/docs.aurora'

const DashboardRoute = DashboardRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDocsStaggerRevealRoute =
  DashboardDocsStaggerRevealRouteImport.update({
    id: '/docs/stagger-reveal',
    path: '/docs/stagger-reveal',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardDocsSilkRoute = DashboardDocsSilkRouteImport.update({
  id: '/docs/silk',
  path: '/docs/silk',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDocsLoadingPageRoute =
  DashboardDocsLoadingPageRouteImport.update({
    id: '/docs/loading-page',
    path: '/docs/loading-page',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardDocsAuroraRoute = DashboardDocsAuroraRouteImport.update({
  id: '/docs/aurora',
  path: '/docs/aurora',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof DashboardIndexRoute
  '/docs/aurora': typeof DashboardDocsAuroraRoute
  '/docs/loading-page': typeof DashboardDocsLoadingPageRoute
  '/docs/silk': typeof DashboardDocsSilkRoute
  '/docs/stagger-reveal': typeof DashboardDocsStaggerRevealRoute
}
export interface FileRoutesByTo {
  '/': typeof DashboardIndexRoute
  '/docs/aurora': typeof DashboardDocsAuroraRoute
  '/docs/loading-page': typeof DashboardDocsLoadingPageRoute
  '/docs/silk': typeof DashboardDocsSilkRoute
  '/docs/stagger-reveal': typeof DashboardDocsStaggerRevealRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_dashboard': typeof DashboardRouteWithChildren
  '/_dashboard/': typeof DashboardIndexRoute
  '/_dashboard/docs/aurora': typeof DashboardDocsAuroraRoute
  '/_dashboard/docs/loading-page': typeof DashboardDocsLoadingPageRoute
  '/_dashboard/docs/silk': typeof DashboardDocsSilkRoute
  '/_dashboard/docs/stagger-reveal': typeof DashboardDocsStaggerRevealRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/docs/aurora'
    | '/docs/loading-page'
    | '/docs/silk'
    | '/docs/stagger-reveal'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/docs/aurora'
    | '/docs/loading-page'
    | '/docs/silk'
    | '/docs/stagger-reveal'
  id:
    | '__root__'
    | '/_dashboard'
    | '/_dashboard/'
    | '/_dashboard/docs/aurora'
    | '/_dashboard/docs/loading-page'
    | '/_dashboard/docs/silk'
    | '/_dashboard/docs/stagger-reveal'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DashboardRoute: typeof DashboardRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/': {
      id: '/_dashboard/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/docs/stagger-reveal': {
      id: '/_dashboard/docs/stagger-reveal'
      path: '/docs/stagger-reveal'
      fullPath: '/docs/stagger-reveal'
      preLoaderRoute: typeof DashboardDocsStaggerRevealRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/docs/silk': {
      id: '/_dashboard/docs/silk'
      path: '/docs/silk'
      fullPath: '/docs/silk'
      preLoaderRoute: typeof DashboardDocsSilkRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/docs/loading-page': {
      id: '/_dashboard/docs/loading-page'
      path: '/docs/loading-page'
      fullPath: '/docs/loading-page'
      preLoaderRoute: typeof DashboardDocsLoadingPageRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/docs/aurora': {
      id: '/_dashboard/docs/aurora'
      path: '/docs/aurora'
      fullPath: '/docs/aurora'
      preLoaderRoute: typeof DashboardDocsAuroraRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardDocsAuroraRoute: typeof DashboardDocsAuroraRoute
  DashboardDocsLoadingPageRoute: typeof DashboardDocsLoadingPageRoute
  DashboardDocsSilkRoute: typeof DashboardDocsSilkRoute
  DashboardDocsStaggerRevealRoute: typeof DashboardDocsStaggerRevealRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardDocsAuroraRoute: DashboardDocsAuroraRoute,
  DashboardDocsLoadingPageRoute: DashboardDocsLoadingPageRoute,
  DashboardDocsSilkRoute: DashboardDocsSilkRoute,
  DashboardDocsStaggerRevealRoute: DashboardDocsStaggerRevealRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  DashboardRoute: DashboardRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
