import { defineConfig } from 'vite-plus/pack'

export default defineConfig({
  entry: {
    index: 'src/index.ts',
    'components/accordion': 'src/components/ui/accordion.tsx',
    'components/alert': 'src/components/ui/alert.tsx',
    'components/alert-dialog': 'src/components/ui/alert-dialog.tsx',
    'components/aspect-ratio': 'src/components/ui/aspect-ratio.tsx',
    'components/avatar': 'src/components/ui/avatar.tsx',
    'components/badge': 'src/components/ui/badge.tsx',
    'components/breadcrumb': 'src/components/ui/breadcrumb.tsx',
    'components/button': 'src/components/ui/button.tsx',
    'components/button-group': 'src/components/ui/button-group.tsx',
    'components/calendar': 'src/components/ui/calendar.tsx',
    'components/card': 'src/components/ui/card.tsx',
    'components/carousel': 'src/components/ui/carousel.tsx',
    'components/chart': 'src/components/ui/chart.tsx',
    'components/checkbox': 'src/components/ui/checkbox.tsx',
    'components/collapsible': 'src/components/ui/collapsible.tsx',
    'components/combobox': 'src/components/ui/combobox.tsx',
    'components/command': 'src/components/ui/command.tsx',
    'components/context-menu': 'src/components/ui/context-menu.tsx',
    'components/dialog': 'src/components/ui/dialog.tsx',
    'components/direction': 'src/components/ui/direction.tsx',
    'components/drawer': 'src/components/ui/drawer.tsx',
    'components/dropdown-menu': 'src/components/ui/dropdown-menu.tsx',
    'components/empty': 'src/components/ui/empty.tsx',
    'components/field': 'src/components/ui/field.tsx',
    'components/hover-card': 'src/components/ui/hover-card.tsx',
    'components/input': 'src/components/ui/input.tsx',
    'components/input-group': 'src/components/ui/input-group.tsx',
    'components/input-otp': 'src/components/ui/input-otp.tsx',
    'components/item': 'src/components/ui/item.tsx',
    'components/kbd': 'src/components/ui/kbd.tsx',
    'components/label': 'src/components/ui/label.tsx',
    'components/menubar': 'src/components/ui/menubar.tsx',
    'components/native-select': 'src/components/ui/native-select.tsx',
    'components/navigation-menu': 'src/components/ui/navigation-menu.tsx',
    'components/pagination': 'src/components/ui/pagination.tsx',
    'components/popover': 'src/components/ui/popover.tsx',
    'components/progress': 'src/components/ui/progress.tsx',
    'components/radio-group': 'src/components/ui/radio-group.tsx',
    'components/resizable': 'src/components/ui/resizable.tsx',
    'components/scroll-area': 'src/components/ui/scroll-area.tsx',
    'components/select': 'src/components/ui/select.tsx',
    'components/separator': 'src/components/ui/separator.tsx',
    'components/sheet': 'src/components/ui/sheet.tsx',
    'components/sidebar': 'src/components/ui/sidebar.tsx',
    'components/skeleton': 'src/components/ui/skeleton.tsx',
    'components/slider': 'src/components/ui/slider.tsx',
    'components/sonner': 'src/components/ui/sonner.tsx',
    'components/spinner': 'src/components/ui/spinner.tsx',
    'components/switch': 'src/components/ui/switch.tsx',
    'components/table': 'src/components/ui/table.tsx',
    'components/tabs': 'src/components/ui/tabs.tsx',
    'components/textarea': 'src/components/ui/textarea.tsx',
    'components/toggle': 'src/components/ui/toggle.tsx',
    'components/toggle-group': 'src/components/ui/toggle-group.tsx',
    'components/tooltip': 'src/components/ui/tooltip.tsx',
    'lib/utils': 'src/lib/utils.ts',
    'hooks/use-mobile': 'src/hooks/use-mobile.ts',
  },
  format: ['esm'],
  dts: {
    tsgo: true,
  },
  deps: {
    neverBundle: ['react', 'react-dom', 'react/jsx-runtime'],
  },
})
